### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by jwilsjustin**
To force bundle to update out-dated versions.

### CODE REVIEW

**Comment by juwlee** [comment]
:+1:

**Comment by jwilsjustin** [comment]
Yey! :smiley:

**Comment by juwlee** [comment]
v1.1.3 has been released. You should be able to (find it on gemspec)[https://rubygems.org/gems/paypal-sdk-rest/versions/1.1.3]

**Comment by jwilsjustin** [comment]
Right on :+1:

**Pull request merged**
