### PR TITLE
specify name-spaced SDK version

### PR DESCRIPTION
**Pull request by jwilsjustin**
#92 #101 

Props to @jziaja for the proposed fix.

### CODE REVIEW

**Comment by jwilsjustin** [comment]
Would it be better to explicitly version this ruby gem in a higher namespace? [Like Sinatra does](https://github.com/sinatra/sinatra/blob/master/lib/sinatra/version.rb). Seems odd to have both the `core` and `rest` directories in this gem, but only the `rest` is versioned. Furthermore, the whole version of them gem is predicated on the `rest` version.

**Comment by jwilsjustin** [comment]
I guess what also adds to the confusion is that the gem name indicates that this is the `REST` implementation, but the repo name implies a larger scope.

**Comment by jziaja** [comment]
Thanks for taking care of this @jwilsjustin ! :+1:  @juwlee is our resident Ruby expert, so I'll let him review this change before merging it in.

To provide some context, the PayPal SDK team recently decided to integrate the Core SDK into all the REST SDKs (along with renaming the repos) to make it easier for this repo to break away from the Classic SDKs that all rely on the Core SDK.  Ideally, this allows us to continue to improve this SDK without impacting the Classic SDKs in the process.  In this respect, it looks like the Ruby SDK still has some updates required before that's possible. :)

**Comment by juwlee** [comment]
Sorry for late response @jwilsjustin . As @jziaja mentioned, Core SDK was merged to REST SDK for separation from classic SDKs because the functionalities required for REST are usually different from those for classic.

The change looks good. Thanks for this PR.

**Pull request merged**
