### PR TITLE
Update payment details

### PR DESCRIPTION
**Pull request by AkshathaBhat4**
Hello Team, 

Hope all is going well.

I have create Pull Request for  payment update issue.

Please check and let me know if there are any modifications.

Thanks & Regards,
Akshatha

### CODE REVIEW

**Comment by juwlee** [comment]
@Akshatha357 thanks! We will have a look at this soon.

**Comment by juwlee** [comment]
@AkshathaBhat4 it looks good to me. Thanks again!

**Comment by DevilalDheer** [comment]
Good Job !!!

**Comment by AkshathaBhat4** [comment]
@juwlee Thanks for quick response :+1:

**Pull request merged**
